#!/bin/bash

# deploy
# temp/alpha version

# brew install python3 node
# ripgrep
# https://github.com/BurntSushi/ripgrep
# sudo dnf install ripgrep
# sudo apt install ripgrep
# pkg install ripgrep
# brew install ripgrep
# pip3 install --user pynvim --upgrade msgpack
# npm install -g neovim
# brew install ctags

# ================================== zsh ===================================== #

echo 'export XDG_CONFIG_HOME="$HOME/.config"' >$HOME/.zshenv
echo 'export ZDOTDIR="$XDG_CONFIG_HOME/zsh"' >>$HOME/.zshenv
echo 'source $ZDOTDIR/zshenv' >>$HOME/.zshenv

ln -s "$(pwd)/home/zshenv" $HOME/.zshenv
# echo '. ~/.config/zsh/zshenv' > ~/.zshenv
ln -s "$(pwd)/config/zsh" ~/.config/
git clone https://github.com/zdharma-continuum/zinit.git ~/.config/zsh/zinit/bin
zsh -c "source $(pwd)/config/zsh/zinit/bin/zinit.zsh && zinit update"
# zsh set as default shell
if ! grep -Fxq "$(which zsh)" /etc/shells; then
	echo "Adding $(which zsh) to /etc/shells"
	echo "$(which zsh)" | sudo tee -a '/etc/shells'
fi
chsh -s "$(which zsh)"

# ================================== bash ==================================== #

ln -s "$(pwd)/home/bashrc" $(HOME)/.bashrc

# ================================= neovim =================================== #

ln -s "$(pwd)/config/nvim" ~/.config/
pip3 install --user neovim pynvim

# Python autocomplete and linting
# https://github.com/palantir/python-language-server
pip3 install --user jedi python-language-server
# py completions and renaming
pip3 install --user rope
# py complexity checking
pip3 install --user mccabe
# py error checking
pip3 install --user pyflakes
# py pep 8 linting
pip3 install --user pycodestyle
# py import sorting and formatting
pip3 install --user pyls-isort
# py code formatting using Black
# https://github.com/ambv/black
pip3 install --user black pyls-black
# py type checking
pip3 install --user pyls-mypy

nvim +PlugInstall +UpdateRemotePlugins +qall

# ================================ ideavim =================================== #

ln -s "$(pwd)/config/ideavim" ~/.config/

# ================================ weechat =================================== #

ln -s "$(pwd)/config/weechat" ~/.config/

# ================================= tmux ===================================== #

ln -s "$(pwd)/config/tmux" ~/.config/
#git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm

# ================================== vim ===================================== #

echo 'source $XDG_CONFIG_HOME/vim/init.vim' >$HOME/.vimrc
ln -s "$(pwd)/config/vim" $HOME/.config/

# ================================== etc ===================================== #

# python extras
#pip3 install bpython

# bin/scripts
ln -s "$(pwd)/bin" "$HOME/"

# Idea Vim key repeat in MacOS
defaults write com.jetbrains.intellij.ce ApplePressAndHoldEnabled -bool false

# TODO: make pbcopy/pbpaste like MacOS using xclip
# echo "test" | tr -d '\n' | xclip -sel clip
# this trims all \n ^^^^^... should trim only final \n
