#!/bin/bash

# deploy
# temp/alpha version

# neovim
ln -s "$(pwd)/config/nvim" ~/.config/
sudo pip3 install jedi neovim
nvim +PlugInstall +UpdateRemotePlugins +qall

# zsh
ln -s "$(pwd)/config/zsh" ~/.config/
echo 'source ~/.config/zsh/zshrc' > ~/.zshrc
git clone https://github.com/zdharma/zinit.git config/zsh/zinit/bin
zsh -c "source $(pwd)/config/zsh/zinit/bin/zinit.zsh && zinit update"


# TODO: make pbcopy/pbpaste like MacOS using xclip
# echo "test" | tr -d '\n' | xclip -sel clip
# this trims all \n ^^^^^... should trim only final \n
