export SHELL=$(which zsh)
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export ZSH="$HOME/.config/zsh"
export ZDOTDIR="$HOME/.config/zsh"
export ADOTDIR="$HOME/.config/zsh/plugins"
export HISTFILE="$HOME/.config/zsh/histfile"
CDPATH=".:$XDG_CONFIG_HOME"
LC_CTYPE=en_US.UTF-8
LC_ALL=en_US.UTF-8

# neovim all the things
export EDITOR=vim
export SUDO_EDITOR=vim
export GIT_EDITOR=vim
export VISUAL=vim
export DIFFPROG="vim -d"
# export MANPAGER='nvim +Man!'
export MANPAGER="/bin/sh -c \"unset PAGER;col -b -x | \
    vim -R -c 'set ft=man nomod nolist' -c 'map q :q<CR>' \
    -c 'map <SPACE> <C-D>' -c 'map b <C-U>' \
    -c 'nmap K :Man <C-R>=expand(\\\"<cword>\\\")<CR><CR>' -\""
export MANWIDTH=999

#export GUILE_LOAD_PATH="/usr/local/share/guile/site/3.0"
#export GUILE_LOAD_COMPILED_PATH="/usr/local/lib/guile/3.0/site-ccache"
export WEECHAT_HOME="$XDG_CONFIG_HOME/weechat"
setopt HIST_IGNORE_SPACE
unsetopt AUTOCD

# Python
if [[ -f /opt/local/bin/python3.10 ]]; then
    export VIRTUALENVWRAPPER_PYTHON='/opt/local/bin/python3.10'
    export VIRTUALENVWRAPPER_VIRTUALENV='/opt/local/bin/virtualenv-3.10'
    export VIRTUALENVWRAPPER_VIRTUALENV_CLONE='/opt/local/bin/virtualenv-clone-3.10'
    source /opt/local/bin/virtualenvwrapper.sh-3.10
fi

# Homebrew GNU coreutils — prepend if present (macOS Homebrew, Apple Silicon + Intel)
for _gnu_dir in \
    /opt/homebrew/opt/coreutils/libexec/gnubin \
    /opt/homebrew/opt/gnu-sed/libexec/gnubin \
    /opt/homebrew/opt/grep/libexec/gnubin \
    /opt/homebrew/opt/findutils/libexec/gnubin \
    /usr/local/opt/coreutils/libexec/gnubin \
    /usr/local/opt/gnu-sed/libexec/gnubin \
    /usr/local/opt/grep/libexec/gnubin \
    /usr/local/opt/findutils/libexec/gnubin
do
    [[ -d "$_gnu_dir" ]] && path=("$_gnu_dir" "$path[@]")
done
unset _gnu_dir

# -U: keep unique, discard duplicates
typeset -U PATH path
path=("/snap/bin" "$path[@]")
path=("/opt/local/bin" "$path[@]")
path=("/opt/local/sbin" "$path[@]")
path=("/opt/local/libexec/gnubin/" "$path[@]")
path=("$HOME/.local/bin" "$path[@]")
path=("$HOME/bin" "$path[@]")
path=("/usr/local/sbin" "$path[@]")
path=("/usr/local/opt/ruby/bin" "$path[@]")
path=("$HOME/Library/Python/3.11/bin" "$path[@]")

export PATH
