export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export ZSH="$HOME/.config/zsh"
export ZDOTDIR="$HOME/.config/zsh"
export ADOTDIR="$HOME/.config/zsh/plugins"
export HISTFILE="$HOME/.config/zsh/histfile"

# neovim all the things
export EDITOR=nvim
export GIT_EDITOR=nvim
export VISUAL=nvim
export DIFFPROG="nvim -d"
export MANPAGER='nvim +Man!'
export MANWIDTH=999

#export GUILE_LOAD_PATH="/usr/local/share/guile/site/3.0"
#export GUILE_LOAD_COMPILED_PATH="/usr/local/lib/guile/3.0/site-ccache"
export WEECHAT_HOME="$XDG_CONFIG_HOME/weechat"
setopt HIST_IGNORE_SPACE

# -U: keep unique, discard duplicates
typeset -U PATH path
path=("$HOME/.local/bin" "$path[@]")
path=("$HOME/bin" "$path[@]")
path=("/usr/local/sbin" "$path[@]")
path=("/usr/local/opt/ruby/bin" "$path[@]")
export PATH
